### ISSUE TITLE
PAS: Certain Fields Answers/input on the PAS Form, are not being displayed on the submitted PAS Form

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#335]
## Browser(s) and Device(s) observed on:
Chrome, IE, Firefox
## What should happen:
When an applicant submits the PAS Form, he/she must be able to view everything he/she has entered and submitted

## What happened instead:
User is not able to see to the following fields upon submission 

![image](https://user-images.githubusercontent.com/57362229/82494178-2fcedc00-9ab7-11ea-8a13-110056459b3d.png)

![image](https://user-images.githubusercontent.com/57362229/82494141-1b8adf00-9ab7-11ea-98f8-eff6bdf1c676.png)

![image](https://user-images.githubusercontent.com/57362229/82494243-49702380-9ab7-11ea-8ac0-23a3e83215a9.png)
![image](https://user-images.githubusercontent.com/57362229/82494285-5725a900-9ab7-11ea-9b6a-dd384611217c.png)

## How to reproduce this bug:

1. Log in to Applicant Portal 
2. Click on the Edit-Pre Application Statement button
3. Navigate to the Project Area Section and Proposed Development site Section, fill in the same fields as mentioned in screenshot, save and submit
4. Navigate back to the Project Area and Proposed Development Site section (error will be seen here)

**Comment by ksinghprod** [comment]
@hannahkates @bean75 not sure if this is considered sev3 or sev2. Please feel free to change if needed

cc @Hemachekuri

**Comment by andycochran** [comment]
This should already be addressed by b4ad95e5b2fe182b31c49ea10433a1b81dfb70f5.

**Comment by ksinghprod** [comment]
This issue it not completely fixed yet @Hemachekuri @hannahkates 

![image](https://user-images.githubusercontent.com/57362229/82579707-2fd4e780-9b5c-11ea-95f0-8d5988d2e674.png)

![image](https://user-images.githubusercontent.com/57362229/82579634-16cc3680-9b5c-11ea-8ba3-95923093acb9.png)

**Comment by andycochran** [comment]
Good catch! There was a bad var in the template. Fixed in #342.

**Comment by ksinghprod** [comment]
Also @andycochran 



![image](https://user-images.githubusercontent.com/57362229/82585998-e8068e00-9b64-11ea-9e96-bfd836ea2df1.png)

**Comment by ksinghprod** [comment]
This issue is fixed but, the Proposed development type selections still are not displayed in the best format

**Comment by ksinghprod** [comment]
This issue is back (the left is the PDF Form generated via CRM). On the Pas Form on the applicant portal, the Conditional field's answer is not displayed on the submitted form 

![image](https://user-images.githubusercontent.com/57362229/85895320-773a3d80-b7c4-11ea-8b41-c6265d0ed6a4.png)

**Comment by ksinghprod** [comment]
This issue is now fixed 

![image](https://user-images.githubusercontent.com/57362229/88097211-d55d0500-cb65-11ea-9f88-86572d296816.png)
